#!/usr/bin/env bash
. "$(dirname "$0")/_/husky.sh"

# Move into project root
BIN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$BIN_DIR"
cd ..

# Exit on errors
set -e

# Run rustywind before commit
if [[ -x node_modules/rustywind/bin/rustywind ]]; then
  ALL_CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '***.html')

  for changed_file in $ALL_CHANGED_FILES
  do
    node_modules/rustywind/bin/rustywind $changed_file --write
  done

  git add $ALL_CHANGED_FILES
else
  echo 'Rustywind is not installed. Please run yarn install before continuing.'
  exit 1
fi

